intial configuration
wolox-training/gs-java pull request #1
Opened 2020-05-20 16:41 UTC by guilleSequeiraWolox

## Summary
1) add initial configuration of the proyect.
2) when run RunTrainingApplic...main() and i go to http://localhost:8081/ the request fail. in the tag screenshots i put the photo.
i think that is correct beacuse i don't specify username and password in the configuration of spring in application.properties.

## Screenshots
![Captura](https://user-images.githubusercontent.com/42941989/82473167-8f20f200-9a9f-11ea-8622-ab28f6666b30.PNG)

## JIRA Card
https://trello.com/c/x8TZ7vwG/16-creacion-del-proyecto-base

2020-05-20 21:21 UTC, darkBasic666 approved these changes

2020-05-20 21:21 UTC, darkBasic666 requested changes
you should request PR to dev

2020-05-21 18:43 UTC, darkBasic666 approved these changes

2020-05-21 20:41 UTC, rabinovichm approved these changes

2020-05-21 21:11 UTC, merged