Add spring security
wolox-training/gs-java pull request #11
Opened 2020-06-09 18:47 UTC by guilleSequeiraWolox

## Summary
Add Spring Security and modify test and all works fine.

## Screenshots

#### Access denied
![image](https://user-images.githubusercontent.com/42941989/84187134-f9f29700-aa67-11ea-91ae-dac4d5624533.png)

#### Access  accepted
![image](https://user-images.githubusercontent.com/42941989/84187171-08d94980-aa68-11ea-8b01-8ab66bd1991e.png)

## JIRA Card
https://trello.com/c/fOyZfLRL/23-integrar-spring-security

2020-06-12 16:21 UTC, darkBasic666 requested changes

2020-06-12 16:21 UTC, darkBasic666 commented on training/src/main/java/wolox/training/models/Users.java
> +    private String password;
The password must be write-only access, you can use this annotation  @JsonProperty(access = Access.WRITE_ONLY)

2020-06-12 16:21 UTC, darkBasic666 commented on training/src/main/java/wolox/training/controllers/UserController.java
You should be has a endpoit to modify the password.

2020-06-17 16:45 UTC, rabinovichm requested changes

2020-06-17 16:45 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    @PutMapping("/users/{id}/password/{password}")
You should **never** send passwords through URLs.

2020-06-17 16:45 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    public Users updatePasswordUser(
The proper way of making a password update is to ask for the old and new password and check that the old password matches with the one on the DB. If you want, you could also ask for _new password confirmation_ and that would be a "muy bien 10 felicitado".

2020-06-17 16:45 UTC, rabinovichm commented on training/src/test/java/wolox/training/controllers/BookControllerTest.java
>  public class BookControllerTest {
Add tests in order to check that a "403 Forbidden" is thrown when a non-authenticated user is trying to get to a closed endpoint.

2020-06-17 16:45 UTC, rabinovichm commented on training/src/test/java/wolox/training/controllers/UsersControllerTest.java
>  public class UsersControllerTest {
Same here

2020-06-18 16:36 UTC, rabinovichm approved these changes
Wonderful ❤️

2020-06-18 17:48 UTC, darkBasic666 requested changes

2020-06-18 17:48 UTC, darkBasic666 commented on training/src/main/java/wolox/training/controllers/UserController.java
> +        if (passwordEncoder.matches(passwordToUpdate.getOldPassword(), user.getPassword())) {
Why do you check the password, when you in the authentication step do that?

2020-06-18 17:56 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/UserController.java
> +        if (passwordEncoder.matches(passwordToUpdate.getOldPassword(), user.getPassword())) {
I told him to do that. When you change your password, even if you are already logged in, you are asked to provide your old password as a security check to confirm that who's trying to update your password is actually you 😋 .

2020-06-18 20:51 UTC, guilleSequeiraWolox commented on training/src/main/java/wolox/training/controllers/UserController.java
> +        if (passwordEncoder.matches(passwordToUpdate.getOldPassword(), user.getPassword())) {
This matcher is to check that really the user logged put the correct old password. 
It is to reinforce security and reaffirm that the person who makes the change is who he says he is.

2020-06-19 14:36 UTC, darkBasic666 approved these changes

2020-06-19 14:42 UTC, merged