Access the information of the logged user
wolox-training/gs-java pull request #13
Opened 2020-06-10 20:52 UTC by guilleSequeiraWolox

## Summary
Access the information of the logged user

## Screenshots
![image](https://user-images.githubusercontent.com/42941989/84317395-10215580-ab43-11ea-9cb2-06d697d75a1d.png)

## JIRA Card
https://trello.com/c/xCffaixo/27-acceder-a-la-informaci%C3%B3n-del-user-logueado

2020-06-12 17:07 UTC, darkBasic666 requested changes

2020-06-12 17:07 UTC, darkBasic666 commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    @GetMapping("/username")
maybe /me or /user is a better resource name

2020-06-17 17:47 UTC, rabinovichm approved these changes

2020-06-18 14:00 UTC, darkBasic666 approved these changes

2020-06-18 14:01 UTC, darkBasic666 commented
Add tests

2020-06-19 18:20 UTC, merged