add swagger
wolox-training/gs-java pull request #7
Opened 2020-05-28 16:04 UTC by guilleSequeiraWolox

## Summary
Add swagger

## Screenshots
![Captura](https://user-images.githubusercontent.com/42941989/83165254-9ff6e680-a0e3-11ea-8fc1-5343373f6d66.PNG)

## JIRA Card
https://trello.com/c/JhAbIs9o/40-swagger

2020-05-28 20:21 UTC, darkBasic666 requested changes

2020-05-28 20:21 UTC, darkBasic666 commented on training/src/main/java/wolox/training/controllers/BookController.java
> +        @ApiResponse(code = 200, message = "find a book")
Add bad request case.

2020-05-29 19:38 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/BookController.java
> +        @ApiResponse(code = 200, message = "Succesfully find all books"),
English tip: "succes**s**fully **found** all books"

2020-05-29 19:40 UTC, rabinovichm approved these changes
Nice work ❤️

2020-06-01 19:49 UTC, merged