add guava in project
wolox-training/gs-java pull request #8
Opened 2020-05-28 17:21 UTC by guilleSequeiraWolox

## Summary
Add  Preconditions de Guava in setters

## Screenshots
N/A

## JIRA Card
https://trello.com/c/RMZ8KR1T/29-agregar-validaci%C3%B3n-de-precondiciones-a-los-setters

2020-05-28 19:27 UTC, darkBasic666 requested changes

2020-05-28 19:27 UTC, darkBasic666 commented on training/src/main/java/wolox/training/models/Book.java
>      public void setId(long id) {
Id us autogenerate, you should't hava a setId

2020-05-28 19:27 UTC, darkBasic666 commented on training/src/main/java/wolox/training/models/Book.java
>      @ApiModelProperty(notes = "isbn of book")
Add @NotNull Annotation

2020-05-29 19:57 UTC, rabinovichm requested changes
Nice Job! Just two little improvements 😋 

I will also leave you [this link](https://www.baeldung.com/java-bean-validation-not-null-empty-blank) so you could quickly know the magic of @NotNull annotation and it's scope. (It's okay to use @NotNull, is not a correction, it's just a nerdy tip 🤓 )

2020-05-29 19:57 UTC, rabinovichm commented on training/src/main/java/wolox/training/models/Book.java
>      public void setPages(Integer pages) {
To make it more robust, you should also check that the number of pages is greater than 0.

2020-05-29 19:57 UTC, rabinovichm commented on training/src/main/java/wolox/training/models/Users.java
> +        Preconditions.checkNotNull(birthdate, message);
You could also check that the passed birthdate is previous than the actual date

2020-06-01 17:57 UTC, rabinovichm approved these changes
Nice job!

2020-06-01 19:56 UTC, merged